In [2]:
import numpy as np
def stock2all(a):
    b = a.swapaxes(0, 2)
    c = b.reshape(b.shape[0], -1)
    d = c.T
    return d

a = np.array(range(27)).reshape((3, 3, 3))
b = stock2all(a)


In [3]:
b

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20],
       [ 3,  4,  5],
       [12, 13, 14],
       [21, 22, 23],
       [ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26]])

In [4]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
a = np.array(range(27)).reshape((3, 3, 3))
b = a.reshape((a.shape[0], -1))

In [6]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])