In [1]:
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import tensorflow as tf
import os

%matplotlib inline 
plt.rcParams['font.sans-serif']=['SimHei'] #用来正常显示中文标签
plt.rcParams['axes.unicode_minus']=False #用来正常显示负号
#有中文出现的情况，需要u'内容'

import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]="1"

from datum import *
import model

In [5]:
data = Datum()
data.data_prepare()
data.get_embedding('{}_{}_{}'.format(2006010120160701, 2015070120160701, 'all'))
data.supervised_data_prepare()
data.ic_prepare()

In [4]:
tf.reset_default_graph()
model = Model(3)
model.data_initial(data)
model.data_split()
model.factor_network()
model.test()

/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)


INFO:tensorflow:Restoring parameters from model-2-4/logmodel-20.ckpt
[[ 0.00533119  0.00861297  0.01163525  0.01775976]
 [ 0.0047437   0.00807584  0.01081765  0.015906  ]
 [ 0.00592437  0.00856841  0.01186961  0.01874804]
 [ 0.00545946  0.00869125  0.01172782  0.01796151]
 [ 0.00544185  0.00870351  0.0116491   0.01770397]
 [ 0.00535744  0.00862663  0.01137458  0.01736143]
 [ 0.0055055   0.00854918  0.01151551  0.01766453]
 [ 0.00513441  0.00834879  0.01148031  0.01764776]
 [ 0.00545681  0.00869584  0.01148394  0.01744194]
 [ 0.00538434  0.00849437  0.01164859  0.01882644]
 [ 0.00531455  0.00792647  0.0105666   0.01617945]
 [ 0.00517313  0.00810547  0.011003    0.01711503]
 [ 0.00550428  0.0087894   0.01188265  0.01820152]
 [ 0.00563899  0.00892414  0.01214325  0.01881503]
 [ 0.00573653  0.00939034  0.01264649  0.01907944]
 [ 0.00619974  0.00978822  0.01274211  0.01875576]
 [ 0.00639513  0.00802536  0.0096745   0.01474617]
 [ 0.00470926  0.00624155  0.00907467  0.01933415]
 [ 0.00115865

In [1]:
def get_data(start_date, end_date, stock_code):
    price_csv = pd.read_csv('/data/zhige_data/huaxia_embedding/stock_data/'+str(stock_code)+'_price.csv')
    dates = np.array(price_csv['TradingDay'])
    for count in range(len(dates)):
        dates[count] = int(''.join(str(dates[count]).split()[0].split('-')))
    select_index = np.where((dates >= start_date) & (dates < end_date))[0]
    return_price = np.array(price_csv['ClosePrice'][select_index])
    
    feature_csv = pd.read_csv('/data/zhige_data/huaxia_embedding/stock_data/'+str(stock_code)+'_feature.csv')
    dates = np.array(feature_csv['trading_day'])
    for count in range(len(dates)):
        dates[count] = int(''.join(str(dates[count]).split()[0].split('-')))
    select_index = np.where((dates >= start_date) & (dates < end_date))[0]
    return_feature = np.array(feature_csv)[select_index, 1:]  
    
    return return_price, return_feature

In [3]:
num_set = set()
for filename in os.listdir('/data/zhige_data/huaxia_embedding/stock_data/'):
    num = filename.split('_')[0]
    if num in num_set:
        continue
    else:
        num_set.add(num)    
data = Datum()
data.data_prepare() 

day_feature = get_data(20150701, 20160701, 1)[1].shape[0]
day_price = get_data(20150701, 20160701, 1)[0].shape[0]
select_num_set = set()
for num in num_set:
    price, feature = get_data(20150701, 20160701, num)
    if price.shape[0] == day_price and feature.shape[0] == day_feature:
        select_num_set.add(num)   

In [4]:
day_feature = get_data(20150101, 20160101, 1)[1].shape[0]
day_price = get_data(20150101, 20160101, 1)[0].shape[0]
num_set_1 = set()
for num in num_set:
    price, feature = get_data(20150101, 20160101, num)
    if price.shape[0] == day_price and feature.shape[0] == day_feature:
        num_set_1.add(num)

In [5]:
day_feature = get_data(20160101, 20170101, 1)[1].shape[0]
day_price = get_data(20160101, 20170101, 1)[0].shape[0]
num_set_2 = set()
for num in num_set:
    price, feature = get_data(20160101, 20170101, num)
    if price.shape[0] == day_price and feature.shape[0] == day_feature:
        num_set_2.add(num)

In [6]:
day_feature = get_data(20140701, 20150701, 1)[1].shape[0]
day_price = get_data(20140701, 20150701, 1)[0].shape[0]
num_set_3 = set()
for num in num_set:
    price, feature = get_data(20140701, 20150701, num)
    if price.shape[0] == day_price and feature.shape[0] == day_feature:
        num_set_3.add(num)  

In [7]:
day_feature = get_data(20150101, 20160101, 1)[1].shape[0]
day_price = get_data(20150101, 20160101, 1)[0].shape[0]
num_set_4 = set()
for num in num_set:
    price, feature = get_data(20150101, 20160101, num)
    if price.shape[0] == day_price and feature.shape[0] == day_feature:
        num_set_4.add(num)

In [22]:
select_num_set.difference(num_set_2)

set()

In [8]:
day_feature = get_data(20160101, 20180101, 1)[1].shape[0]
day_price = get_data(20160101, 20180101, 1)[0].shape[0]
num_set_5 = set()
for num in num_set:
    price, feature = get_data(20160101, 20180101, num)
    if price.shape[0] == day_price and feature.shape[0] == day_feature:
        num_set_5.add(num)

In [12]:
num_set_5.difference(num_set_2)

set()

In [13]:
select_num_set.difference(num_set_2)

set()

In [14]:
num_set_3.difference(num_set_4)

{'24', '300186'}

In [28]:
len(num_set_2)

2777

In [19]:
a = np.load('/data/zhige_data/huaxia_embedding/embedding/stable_index_2006010120179999_2016010120170101_year.npy')

In [41]:
np.load('/data/zhige_data/huaxia_embedding/embedding/stable_index_2006010120180000_2016010120170101_year.npy').shape

(2776,)

In [36]:
list_stable_stocks = [data.list_stocks[i] for i in a]
for code in num_set_2:
    for _ in range(6-len(code)):
        code = '0' + code   
    if code not in list_stable_stocks:
        print(code)

600610


In [31]:
data.list_stocks[0]

'600176'

In [34]:
len(a)

2776

In [35]:
len(num_set_2)

2777

In [39]:
get_data(20160101, 20170101, 600610)[1].shape

(244, 44)

In [52]:
def embedding(emb, stock_select, season_select):
    day_feature = get_data(stock_select[0], stock_select[1], 1)[1].shape[0]
    day_price = get_data(stock_select[0], stock_select[1], 1)[0].shape[0]
    select_num_set = set()
    for num in num_set:
        price, feature = get_data(stock_select[0], stock_select[1]+20, int(num))
        if price.shape[0] >= day_price and feature.shape[0] >= day_feature:
            select_num_set.add(num)   

    stable_stock_code = set()
    for num in select_num_set:
        code = num
        for _ in range(6-len(code)):
            code = '0' + code     
        if code in stable_stock_code:
            continue
        else:
            stable_stock_code.add(code)    
    
    stable_index = []
    for idx, stock in enumerate(data.list_stocks):
        if stock in stable_stock_code:
            stable_index.append(idx)
    stable_index = np.array(stable_index)    
    list_stable_stocks = [data.list_stocks[i] for i in stable_index]  
    print(len(stable_index))

In [53]:
embedding([20060101, 20160701], [20160101, 20170101], 'year')

2776
